### ISSUE TITLE
Adding custom attribute like custom class to input fields

### ISSUE THREAD

**Issue by serior** [tonytan4ever/Bootstrap-Form-Builder-JV3#21]
I want save the form into db and render it with my custom code. Therefore i need for each form element a field into popup, where i can write custom attributes like class etc.
Is there a way to do it?

**Comment by tonytan4ever** [comment]
You can modify the templates in this location:
https://github.com/tonytan4ever/Bootstrap-Form-Builder-V3V4/tree/master/assets/js/templates/snippet
By adding your custom class there.

**Comment by serior** [comment]
It seems to be simple. Thank you.
