### ISSUE TITLE
how to remove tabs?

### ISSUE THREAD

**Issue by lorvent** [tonytan4ever/Bootstrap-Form-Builder-JV3#26]
Hi Tony,
can you tell me how to remove tabs like `rendered` or add new tabs?

i tried removing all references but it doesn't go away, so we need to compile something or what?

thanks.

**Comment by tonytan4ever-rchealth** [comment]
Look at the code here: https://github.com/tonytan4ever/Bootstrap-Form-Builder-V3V4/blob/master/assets/js/app.js#L22~L50.
You should be able to add/remove/modify all the tabs.

**Comment by tonytan4ever** [comment]
Look at the code here: https://github.com/tonytan4ever/Bootstrap-Form-Builder-V3V4/blob/master/assets/js/app.js#L22~L50.
You should be able to add/remove/modify all the tabs.

**Comment by lorvent** [comment]
oops, i have already tried that but due to cache issue it is not reflecting,
thank you :)
