### ISSUE TITLE
convert the form as json

### ISSUE THREAD

**Issue by thiyagu06** [tonytan4ever/Bootstrap-Form-Builder-JV3#4]
Is it possible to save the form properties as json and save it in db??

**Comment by tonytan4ever** [comment]
What do you mean by "form properties" ? 
If that is the layout and the fields of the code then yes, it is possible.

**Comment by thiyagu06** [comment]
I mean to say that, layout position and attribute values.. also if possible can you share the code??

**Comment by tonytan4ever** [comment]
This is the code of form :
<div class="col-md-6">
          <div class="clearfix">
            <h2>Your Form</h2>
            <hr>
            <div id="build">
              <form id="target" class="form-horizontal">
              </form>
            </div>
          </div>
        </div>
It's in index.html

The layout of all fields are all in assets/js/data.

This is an open source project, so feel free to explore and experience with the code
