### ISSUE TITLE
Validation Issue

### ISSUE THREAD

**Issue by aprnarola** [tonytan4ever/Bootstrap-Form-Builder-JV3#5]
Validation is not working , Using textbox  and click on required, after rendered html page ,no vaalidation applay

**Comment by lorvent** [comment]
Yes, i can confirm that
@tonytan4ever are you still maintaining this repo or got busy with life?

**Comment by tonytan4ever** [comment]
I will fix this issue by next week.

**Comment by lorvent** [comment]
wow, that would be great! :+1:

**Comment by tonytan4ever** [comment]
Fixed:
https://github.com/tonytan4ever/Bootstrap-Form-Builder-JV3/commit/c1d617f8377e64a8d50c66b613dbf30634bde1c0
